#config_version=6

mode: # this mode declaration indicates when base mode will start and stop
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

event_player: # this event player indicates when other modes will be activated
  mode_base_started:
    - start_mode_bumpers
  mode_base_will_stop:
    - stop_mode_bumpers
  left_lane_hit: start_mode_hurryup

shots: # this defines shots that are active in base mode
  center_lane_exit:
    switches: s_center_lane_exit

slide_player: # this is the slide (scene) that Godot will play during base mode
  mode_base_started: base